trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  # solution: '**/*.sln'
  solution: 'GoMartApplication.sln'
  projectPath: 'GoMartApplication\GoMartApplication.csproj'
  outputPath: '$(Build.ArtifactStagingDirectory)\AppOutput'
  copyToPath: 'C:\agent\MyApp'

stages:
- stage: Build
  jobs:
  - job: BuildDesktopApp
    displayName: 'Build .NET Desktop App'
    steps:

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:Configuration=$(buildConfiguration)'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Build Output to Staging Directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\MyApp\bin\$(buildConfiguration)'
        Contents: '**\*'
        TargetFolder: '$(outputPath)'

    - task: CopyFiles@2
      displayName: 'Copy to Final Target Directory'
      inputs:
        SourceFolder: '$(outputPath)'
        Contents: '**\*'
        TargetFolder: '$(copyToPath)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(outputPath)'
        ArtifactName: 'drop'
